schedule:
  monday: "09:00"
  tuesday: "12:00"
  wednesday: "19:00"
  thursday: "10:00"
  friday: "18:00"
  saturday: "11:00"
  sunday: "20:00"

roles:
  - ceo
  - buscador
  - escritor
  - editor
  - creador_imagenes
  - publicador
  - asistente_comunitario
